version: "3"
services:
  app:
    build:
      context: .
    command: bundle exec puma -C config/puma.rb -e production
    # command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/RecipeApp
      - bundle:/usr/local/bundle
      - public-data:/RecipeApp/public
      - tmp-data:/RecipeApp/tmp
      - log-data:/RecipeApp/log
      - /RecipeApp/.git
    networks:
      - recipeapp-network
    depends_on:
      # - db
      - chrome

  chrome:
    image: selenium/standalone-chrome:latest
    shm_size: 256m
    ports:
      - 4444:4444
    networks:
      - recipeapp-network

  # db:
  #   image: mysql:8.0
  #   environment:
  #     MYSQL_ROOT_PASSWORD: password
  #     MYSQL_USER: user
  #     MYSQL_PASSWORD: password
  #     MYSQL_DATABASE: ShareRecipe_development
  #   command: --default-authentication-plugin=mysql_native_password
  #   volumes:
  #     - mysql-data:/var/lib/mysql
  #   networks:
  #     - recipeapp-network

  web:
    build:
      context: ./nginx_docker
    volumes:
      - public-data:/RecipeApp/public
      - tmp-data:/RecipeApp/tmp
    ports:
      - 80:80
    depends_on:
      - app
    networks:
      - recipeapp-network

volumes:
  bundle:
  mysql-data:
  public-data:
  log-data:
  tmp-data:

networks:
  recipeapp-network:
    external: true
