version: "3"
services:
  app:
    build:
      context: .
    # =========ローカルと本番切り替え===========
    command: bundle exec puma -C config/puma.rb -e production
    # command: bundle exec puma -C config/puma.rb
    # ==========================================

    volumes:
      - .:/RecipeApp
      - bundle:/usr/local/bundle
      - public-data:/RecipeApp/public
      - tmp-data:/RecipeApp/tmp
      - log-data:/RecipeApp/log
    networks:
      - recipeapp-network
    depends_on:
      # - db
      - chrome
    ports:
      - 3000:3000

  chrome:
    image: selenium/standalone-chrome:latest
    shm_size: 256m
    ports:
      - 4444:4444
    networks:
      - recipeapp-network

  # =========ローカルと本番切り替え===========
  # db:
  #   image: mysql:5.7
  #   environment:
  #     MYSQL_ROOT_PASSWORD: password
  #     MYSQL_USER: user
  #     MYSQL_PASSWORD: password
  #     MYSQL_DATABASE: RecipApp_development
  #   volumes:
  #     - mysql-data:/var/lib/mysql
  #     - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
  #   command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  #   ports:
  #     - "3307:3306"
  #   networks:
  #     - recipeapp-network
  # ======================================

  web:
    build:
      context: ./nginx_docker
    volumes:
      - public-data:/RecipeApp/public
      - tmp-data:/RecipeApp/tmp
    ports:
      - 80:80
    depends_on:
      - app
    networks:
      - recipeapp-network

volumes:
  bundle:
  public-data:
  tmp-data:
  log-data:
  mysql-data:

networks:
  recipeapp-network:
    external: true
