version: "3"
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "4306:3306"

  web:
    tty: true
    stdin_open: true
    build: .
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails db:migrate && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    volumes:
      - .:/myproject
      - bundle:/usr/local/bundle
      # 1. exclude volumes
      - /myproject/vendor
      - /myproject/tmp
      - /myproject/log
      - /myproject/.git
    depends_on:
      - db

volumes:
  mysql-data:
  bundle:
