# MySQL. Versions 5.5.8 and up are supported.
#

default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: db

development:
  <<: *default
  database: ShareRecipe_development

test:
  <<: *default
  database: ShareRecipe_test

production:
  <<: *default
  host: <%= ENV['APP_DATABASE_HOST'] %>
  database: ShareRecipe_production
  username: ShareRecipe
  password: <%= ENV['SHARERECIPE_DATABASE_PASSWORD'] %>
